version: '3.8'

services:
  investment-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-dashboard
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Lisbon
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      - API_NINJAS_KEY=${API_NINJAS_KEY:-}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

networks:
  default:
    driver: bridge
